disabled = false
languageCode = 'en'
languageName = 'English'
title = 'Ayahuasca Nete' # This will go in the Header as well
contentDir = "content/en"


# Change single params to "false" to remove from rendering
[params]
  subtitle = "Paoyhan, Peru" # This goes in the header and in the site title
  # PAGES
  [params.homepage]
    # Notice that SEO meta tags (what appears in google search results) can be set
    # in individual pages frontmatters `/content/<page>`
    ###
    title = "Ayahuasca Nete"
    # You can use some markdown safely here as long as you don't include line breaks
    intro= """
### Authentic Ayahuasca dietas in the Amazon.
___

Retreats are offered as needed.

What makes our healing center truly special is that it is **family-owned and operated by the Shipibo people**, the guardians of ancestral plant medicine. Unlike many other centers, our deep-rooted connection to this tradition grants unparalleled access to authentic Shipibo shamans, offering you a **profound and immersive healing experience**.

Nestled in a **serene location in Paoyhan**, our retreats provide a secluded and intimate setting. Here, you can fully embrace the wisdom of the plants, guided by generations of Shipibo healers in a space designed for deep transformation and self-discovery.
        """
    mainButton = "Packages"
    mainButtonRef = "packages" # Slug of the page
    secondButton = "Contact Us"
    secondButtonRef = "contact" # Slug of the page

[params.contact]
  title = "Get in touch!"
#  formCallToAction = "[Form description]"
#  socialCallToAction = "[Social call to action]" # These are the same as in [params.social]
  [params.contact.form]
    formspreeLink = "https://formspree.io/f/xkgnrajg"
    firstname = "First Name*"
    lastname = "Last Name*"
    email = "E-mail*"
    phone = "Phone Number"
    Inquiry = "Inquiry*"
    submitBtn = "Submit"

[params.packages]
  title = "Packages"

  intro = """Retreats are offered as needed.

---
"""

    mainButton = "Contact Us"
    mainButtonRef = "Contact" # Slug of the page

  description = """
## **Included:**

* **Food and Drink** - We take care of all your meals and drinks so you can focus your energy on immersing in the experience.
* **Plant Sauna** – Sweat out toxins and absorb the medicinal properties of Amazonian plants in a deeply purifying experience.
* **Flower Bath** – A sacred ritual using fragrant flowers and healing plants to cleanse your body.
* **Medicines** - Ayahuasca, your master plant and mapacho will be authentically and directly sourced for you.

![Nature](/img/nature-1.jpg "img-fluid rounded shadow img-content-centered")

## What you're paying for

Your cost goes towards your stay at the accommodation.
We don't charge for medicine or treatments. By doing it this way, it means we assess your individual needs, only giving you the treatments and medicines we believe are right for you.
  """

[params.guide]
title = "Guide"
description = """
_Why embark on this journey?_

![Bird](/img/bird.jpg "img-fluid rounded shadow img-content-center mt-3 mb-4")
### Healing

Our retreat is a sanctuary for those seeking profound healing - whether you are:

* Releasing **past traumas**
* Finding clarity at a **life crossroads**
* Seeking relief from **physical ailments**

## Learning {class="mt-5"}

Open your mind to connect with the power of plants:

* Learn the **Shipibo language and traditions.**
* Resonate with, and be **guided by the plants**.
* Develop your own **spiritual abilities.**

![Nature](/img/nature-3.jpg "img-fluid rounded shadow img-content-right mt-3 mb-4")
## Ayahuasca Ceremonies {class="mt-5"}

Held **every two or three nights**, depending on your stay, our ceremonies are guided by **powerful icaros** - sacred healing songs sung by the shamans, to help navigate your journey.

Here, under the watchful care of experienced healers, you will explore the depths of your consciousness and receive the medicine’s wisdom in a **safe and supportive space**.

## Dieta {class="mt-5"}

_What is a dieta?_

This is a dedicated period where the person follows specific dietary behaviours to strengthen their spiritual connection with the plant.

![Nature](/img/nature-2.jpg "img-fluid rounded shadow img-content-right mt-3 mt-md-5")
## Food {class="mt-5"}

We abstain from:

* Salt
* Sugar
* Oil
* Spices
* Red meat
* Pork


We eat:

* Grains
* Fruit
* Vegetables
* Eggs
* Chicken
* Fish

*We can cater to **vegan and vegetarian** diets.*

### Restrictions {class="mt-5"}

* Limited conversation.
* Focus on the connection with the plant.
* No internet or books.

### Preparation {class="mt-5"}

We encourage starting the food diet five days ahead of arrival.
Be off medications and abstain from sexual activity.

### Post Dieta {class="mt-5"}

To bring your journey to a close and reap the best benefits, continue the dieta for approximately five days post retreat, depending on length of your dieta.

![Nature](/img/nature-4.jpg "img-fluid rounded shadow img-content-center mt-3 mb-4")
### Plants

In your dieta, you will connect with another plant. These are called **teacher plants or master plants**.

Different plants have different unique properties. We'll discuss with you when you arrive to determine your plant. Please let us know if there's a specific plant you're called to.

Examples of some of the plants we work with:

* Bobinsana
* Chiric Sanango
* Renaquilla
* Renaco
* Tamamoori
* Noya Rao

![Building](/img/building-2.jpg "img-fluid rounded shadow img-content-left my-2 my-md-3 mt-lg-0")
### Length

* We recommend a **minimum of a week** for the true immersive experience and full benefits.
* We find most people do **up to 30 days**.
* Certain plants, like trees, call for a longer dieta.
* If you do 20 days or more, you may diet two plants, one after the other.

## Ayahuasca Retreat: A Transformational Journey {class="mt-5" style="clear:both"}

If you're new to ayahuasca or have commitments at home, an **ayahuasca retreat** offers a powerful way to experience the medicine without the deeper commitment of a plant dieta.

A **plant dieta** requires **completing** the full process once started, as it is a crucial part of forming a profound spiritual connection with specific healing plants. However, an ayahuasca retreat **follows the same ceremonial process without opening a dieta**, allowing for flexibility and the option to stop if needed.

This makes an ayahuasca retreat an ideal choice if you:

* Are exploring ayahuasca for the first time
* Have responsibilities that may require you to leave early
* Want to experience the healing power of ayahuasca without a long-term dieta commitment

![Bird](/img/bird-2.jpg "img-fluid rounded shadow img-content-center mt-3")

"""


[params.location]
  title = "Location"
 description = """We’re located outside of the village of Paoyhan, in a **peaceful space** on the edge of the jungle."""
  travel = """# Traveling To Us

### Arrival:

* Arrive in Pucallpa at least **the day before** your first ceremony and stay there overnight.
* At 7am, you'll be met by someone from the family who will help you board the boat to us at 8am \\- this is approx 4 hours down the Ucayali River.
* You’ll disembark in Paoyhan and be picked up by a family member who will take you directly to the center.

### Departure:

* Depart **the night after** your last ceremony, or longer if you'd like to stay.
* The boat leaves at approximately 11pm and arrives in Pucallpa at 3:30am. We recommend booking a stay or flight for this day.

The boat is 100 Soles (~$30) each way.
"""

 buttonText = "Find flights to Pucallpa, Peru"
 buttonLink = "https://www.google.com/travel/flights"
 mapLink = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d31619.904959217703!2d-75.0292585!3d-7.8438707999999995!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x91a4a1fc58da4da3%3A0x9cdf2d43604c166e!2sKene%20Nete%20Healing%20Center!5e0!3m2!1sen!2sus!4v1731264241456!5m2!1sen!2sus" # google maps "embed" link here


[params.about]
  title = "About Us"

  olinda = """### Olinda
Olinda has a wealth of knowledge and experience, starting her path as a shaman over 20 years ago. She has spent years dieting master plants including Bobinsana, Chiric Sanango, Renaquilla, Tamamoori, and Noya Rao.

She is now a master shaman and Great Grandmother. She is renowned for her wisdom of the plants and in ceremonies helps people find their strength to complete their journeys.
"""

  other = """
### Other Shamans
Olinda is supported by other shamans in her extended family that join the ceremonies. They bring their own wealth of knowledge and unique skill sets.

---

![Bananas](/img/bananas.jpg "img-fluid rounded shadow img-content-right")
### Family {class="mt-4"}
It’s a family-run center, with the rest of the staff being her adult children, their partners, and her grandchildren. They provide support during ceremonies, assist with the cooking and cleaning, as well as helping with construction and maintenance.
"""


[params.socials]
  enabled = false # enables/disables the whole social section in the footer
  callToAction= "Get connected with us on social networks >"
      [[params.socials.link]]
        name = "facebook"
        link = "[facebook]"
      [[params.socials.link]]
        name = "instagram"
        link = "[instagram]"
      [[params.socials.link]]
        name = "whatsapp"
        link = "[instagram]"
      # You can add other socials here by copypasting the above section and
      # selecting the right name for the icon from here https://icons.getbootstrap.com/

[params.footer]
  [params.footer.navigate]
  heading = "Navigate"   
  [params.footer.contacts]
  enabled = false # enables/disables the whole contacts section in footer
  heading = "Contact"
  mail = "jungroth@gmail.com"
  phone = "+1-707-812-4818"
  
[params.notfound]
  title = "404, page not found" # text for 404 page

[params.single] # for posts pages (visible only if posts are rendered)
  similarContent= "Similar Content"
  toc= "Table of Contents"

[menus]
# PageRef should refer to the "translationKey" in `/content/<page>` frontmatter, names can be changed freely
  [[menus.main]]
  name = "Home"
  pageRef = "/"
  weight = 1
  [[menus.main]]
  name = "Guide"
  pageRef = "pages/guide"
  weight = 2
  [[menus.main]]
  name = "Packages"
  pageRef = "pages/packages"
  weight = 3
  [[menus.main]]
  name = "About Us"
  pageRef = "pages/about"
  weight = 4
  [[menus.main]]
  name = "Location"
  pageRef = "pages/location"
  weight = 5
  [[menus.main]]
  name = "Contact"
  pageRef = "pages/contact"
  weight = 6
