disabled = false
languageCode = 'en'
languageName = 'English'
title = 'Paoyhan Ayahuasca' # This will go in the Header as well
contentDir = "content/en"


# Change single params to "false" to remove from rendering
[params]
  subtitle = "Ucayali River, Peru" # This goes in the header and in the site title
  # PAGES
  [params.homepage]
    # Notice that SEO meta tags (what appears in google search results) can be set
    # in individual pages frontmatters `/content/<page>`
    ###
    title = "Paoyhan Ayahuasca"
    # You can use some markdown safely here as long as you don't include line breaks
    intro= """
### Authentic Ayahuasca dietas in the Amazon.
___
What makes our healing center truly special is that it is **family-owned and operated by the Shipibo people**, the guardians of ancestral plant medicine. Unlike many other centers, our deep-rooted connection to this tradition grants unparalleled access to authentic Shipibo shamans, offering you a **profound and immersive healing experience**.

Nestled in a **serene location in Paoyhan**, our retreats provide a secluded and intimate setting. Here, you can fully embrace the wisdom of the plants, guided by generations of Shipibo healers in a space designed for deep transformation and self-discovery.
        """
    mainButton = "Packages"
    mainButtonRef = "packages" # Slug of the page
    secondButton = "Contact Us"
    secondButtonRef = "contact" # Slug of the page

[params.contact]
  title = "Get in touch!"
#  formCallToAction = "[Form description]"
#  socialCallToAction = "[Social call to action]" # These are the same as in [params.social]
  [params.contact.form]
    formspreeLink = "https://formspree.io/f/xkgnrajg"
    firstname = "First Name*"
    lastname = "Last Name*"
    email = "E-mail*"
    phone = "Phone Number"
    Inquiry = "Inquiry*"
    submitBtn = "Submit"

[params.packages]
  title = "Packages"
  description = """[Packages]"""
  [params.packages.list]
    [params.packages.list.0]
      title= "8 Day Ayahuasca Retreat"
      description= "[8 days]"
    [params.packages.list.01]
      title = "11 Day Master Plant Dieta"
      description= "[11 days]"
    [params.packages.list.02]
      title = "20 Day Master Plant Dieta"
      description= "[20 days]"
    [params.packages.list.03]
      title = "32 Day Master Plant Dieta"
      description= "[32 Days]"
    [params.packages.list.04]
      title = "Custom Stays"
      description= "We can accomodate different lengths or longer stays. Just ask!"

[params.location]
  title = "Location"
 description = """We’re located outside of the village of Paoyhan, in a **peaceful space** on the edge of the jungle."""
  travel = """# Traveling To Us

### Arrival:

* Arrive in Pucallpa at least **the day before** your first ceremony and stay there overnight.
* At 7am, you'll be met by someone from the family who will help you board the boat to us at 8am \\- this is approx 4 hours down the Ucayali River.
* You’ll disembark in Paoyhan and be picked up by a family member who will take you directly to the center.

### Departure:

* Depart **the night after** your last ceremony, or longer if you'd like to stay.
* The boat leaves at approximately 11pm and arrives in Pucallpa at 3:30am. We recommend booking a stay or flight for this day.

The boat is 100 Soles (~$30) each way.
"""

 buttonText = "Find flights to Pucallpa, Peru"
 buttonLink = "https://www.google.com/travel/flights"
 mapLink = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d31619.904959217703!2d-75.0292585!3d-7.8438707999999995!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x91a4a1fc58da4da3%3A0x9cdf2d43604c166e!2sKene%20Nete%20Healing%20Center!5e0!3m2!1sen!2sus!4v1731264241456!5m2!1sen!2sus" # google maps "embed" link here


[params.about]
  title = "About Us"

  olinda = """### Olinda
Olinda has a wealth of knowledge and experience, starting her path as a shaman over 20 years ago. She has spent years dieting master plants including Bobinsana, Chiric Sanango, Renaquilla, Tamamoori, and Noya Rao.

She is now a master shaman and Great Grandmother. She is renowned for her wisdom of the plants and in ceremonies helps people find their strength to complete their journeys.
"""

  other = """### Other Shamans
Olinda is supported by other shamans in her extended family that join the ceremonies. They bring their own wealth of knowledge and unique skill sets.

### Family
It’s a family-run center, with the rest of the staff being her adult children, their partners, and her grandchildren. They provide support during ceremonies, assist with the cooking and cleaning, as well as helping with construction and maintenance.
"""


[params.socials]
  enabled = true # enables/disables the whole social section in the footer
  callToAction= "Get connected with us on social networks >"
      [[params.socials.link]]
        name = "facebook"
        link = "[facebook]"
      [[params.socials.link]]
        name = "instagram"
        link = "[instagram]"
      [[params.socials.link]]
        name = "whatsapp"
        link = "[instagram]"
      # You can add other socials here by copypasting the above section and
      # selecting the right name for the icon from here https://icons.getbootstrap.com/

[params.footer]
  [params.footer.navigate]
  heading = "Navigate"   
  [params.footer.contacts]
  enabled = true # enables/disables the whole contacts section in footer
  heading = "Contact"
  mail = "jungroth@gmail.com"
  phone = "+1-707-812-4818"
  
[params.notfound]
  title = "404, page not found" # text for 404 page

[params.single] # for posts pages (visible only if posts are rendered)
  similarContent= "Similar Content"
  toc= "Table of Contents"

[menus]
# PageRef should refer to the "translationKey" in `/content/<page>` frontmatter, names can be changed freely
  [[menus.main]]
  name = "Home"
  pageRef = "/"
  weight = 1
  [[menus.main]]
  name = "Packages"
  pageRef = "pages/packages"
  weight = 2
  [[menus.main]]
  name = "About Us"
  pageRef = "pages/about"
  weight = 3
  [[menus.main]]
  name = "Location"
  pageRef = "pages/location"
  weight = 4
  [[menus.main]]
  name = "Contact"
  pageRef = "pages/contact"
  weight = 5
